use std::io::Write;
use std::sync::{LazyLock, Mutex};
use std::time::Duration;

use regex::Regex;
use serde::Serialize;
use tauri::{AppHandle, Emitter};
use tauri_plugin_shell::process::{CommandChild, CommandEvent};
use tauri_plugin_shell::ShellExt;
use tokio::time::timeout;

use crate::error::AppError;
use crate::pm3::output_parser::strip_ansi;

/// Payload emitted as `pm3-output` events for the live terminal panel.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Pm3OutputPayload {
    pub text: String,
    pub is_error: bool,
}

/// Emit raw PM3 output to the frontend terminal panel AND write to debug log.
pub fn emit_output(app: &AppHandle, text: &str, is_error: bool) {
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let _ = app.emit(
            "pm3-output",
            Pm3OutputPayload {
                text: trimmed.to_string(),
                is_error,
            },
        );
    }
    // Also append to the debug log file so the developer can inspect it
    // after the fact without needing to watch the live terminal.
    let log_dir = std::path::PathBuf::from("D:\\kilocode\\Phosphor-debug\\Phosphor2.2GUI\\logs");
    let _ = std::fs::create_dir_all(&log_dir);
    // Find next available log number
    let mut max = 0u32;
    if let Ok(entries) = std::fs::read_dir(&log_dir) {
        for entry in entries.flatten() {
            if let Some(name) = entry.file_name().to_str() {
                if let Ok(n) = name.trim_end_matches(".md").parse::<u32>() {
                    max = max.max(n);
                }
            }
        }
    }
    let path = log_dir.join(format!("{:03}.md", max + 1));
    let mut f = match std::fs::File::create(&path) {
        Ok(f) => f,
        Err(_) => return,
    };
    let _ = writeln!(f, "# Test Log #{:03}\n", max + 1);
    let _ = writeln!(f, "## PM3 Output\n");
    let _ = writeln!(f, "```\n{}\n```\n", text);
    let _ = writeln!(f, "---\n");
    let _ = writeln!(f, "*Generated by Phosphor debug logger*");
}

/// Maximum time to wait for a PM3 subprocess to complete (30 seconds).
const PM3_COMMAND_TIMEOUT: Duration = Duration::from_secs(30);

/// Timeout for the LF/HF scan sweeps.
///
/// These are full-spectrum searches, not quick tag probes. Measured on the
/// rdv4 with a T5577 and a legacy iCLASS card:
///   lf search  ~9-10.5s   (exit -10 on a blank T5577, after printing the chipset)
///   hf search  ~10.8s     (exit 0 on a legacy iCLASS card)
///
/// The 8s `DETECT_COMMAND_TIMEOUT` used to be applied here, which was far too
/// short: both searches were killed mid-run, the aborted child kept COM24 open,
/// and the following search failed with "invalid serial port". That surfaced to
/// the user as "No card found" for a card that was on the antenna. 30s restores
/// the pre-regression behaviour.
const SEARCH_COMMAND_TIMEOUT: Duration = Duration::from_secs(30);

/// Shorter timeout for tag-detection commands (`hf 14b info`, `hf 15c info`, etc.).
/// PM3 hangs when no tag of the requested type is on the reader — a 30s wait
/// per panel click is unacceptable. These are single-protocol probes rather than
/// full sweeps; measured at 1.9-3.8s (emrtd 2.1, 15 2.1, 14b 2.7, iclass 3.4,
/// felica 3.8, legic 1.9). 8s is generous.
const DETECT_COMMAND_TIMEOUT: Duration = Duration::from_secs(8);

/// Timeout for the long-running brute-force / dictionary-attack commands.
///
/// These are NOT quick panel probes. `lf t55xx chk` measured 26.8s on this
/// hardware -- it loads ~123 passwords from t55xx_default_pwds.dic and tests
/// each one against the tag ("[+] time in check pwd 26 seconds"). That is
/// uncomfortably close to `PM3_COMMAND_TIMEOUT` (30s): on a slower run it hit
/// the cap, the PM3 child was killed mid-brute-force, and because the child
/// owns COM24 the NEXT command failed with "invalid serial port", which the
/// user saw as the Chk-pwds button reporting a device error.
///
/// `lf t55xx bruteforce`, `hf 15 bruteforce`, `hf mf bruteforce` and
/// `hf mfu desbrute` are the same class of operation and can run for many
/// minutes on a real attack. 15 minutes leaves generous headroom over the
/// observed 27s while still bounding the worst case.
const LONG_COMMAND_TIMEOUT: Duration = Duration::from_secs(15 * 60);

/// Per-port probe timeout during device detection — much shorter than the
/// normal command timeout so scanning 40 COM ports doesn't take 20 minutes.
/// A real PM3 responds to `hw version` in well under 2 seconds on a live port.
const DETECT_TIMEOUT: Duration = Duration::from_secs(3);

/// Returns the ordered list of Tauri shell scope names to try when spawning the
/// PM3 binary. The first entry (`"proxmark3"`) resolves via PATH; subsequent
/// entries are platform-specific absolute paths registered in the shell scope.
/// This lets users who installed PM3 outside of PATH (common on Windows) still
/// use the app without manually editing their system PATH.
fn pm3_scope_names() -> Vec<&'static str> {
    let mut names = vec!["proxmark3"];

    if cfg!(target_os = "windows") {
        names.push("proxmark3-win-c");
        names.push("proxmark3-win-progfiles");
    } else if cfg!(target_os = "macos") {
        names.push("proxmark3-mac-local");
        names.push("proxmark3-mac-brew");
    } else {
        // Linux and other unix-like
        names.push("proxmark3-linux-local");
        names.push("proxmark3-linux-usr");
    }

    names
}

/// Validates that a port string matches expected serial port patterns.
/// Accepts COM1-COM256+ (Windows), /dev/ttyACM0-99, /dev/ttyUSB0-99 (Linux),
/// and /dev/tty.usbmodem* (macOS).
static PORT_RE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"^(COM[1-9]\d*|/dev/tty(ACM|USB)\d{1,2}|/dev/tty\.usbmodem\w+)$")
        .expect("bad port regex")
});

/// Internal PM3 execution that does NOT emit to the frontend.
/// Handles: port validation, command sanitization, sidecar fallback, PATH lookup,
/// process spawn, output collection, ANSI stripping, and timeout.
/// Returns the cleaned output string on success.
///
/// `wait` controls how long to wait for the subprocess. Pass
/// `PM3_COMMAND_TIMEOUT` (30s) for normal commands and `DETECT_COMMAND_TIMEOUT`
/// (8s) for tag-detection commands where PM3 hangs when no tag is present.
/// `tolerate_nonzero` controls what happens when PM3 exits with a non-zero code.
/// PM3 returns -2/-7/-10 for "no tag found" *even when it did detect something it
/// could not fully classify*. Concretely, `lf search` on a T5577 prints
/// `[-] No known 125/134 kHz tags found!` then `[+] Chipset... T55xx`, then exits
/// -10. Callers that can interpret partial detections (the scan wizard) set this
/// to true so the output survives and the parser decides. Everyone else keeps the
/// strict error path.
async fn execute_pm3(
    app: &AppHandle,
    port: &str,
    cmd: &str,
    wait: Duration,
    tolerate_nonzero: bool,
) -> Result<String, AppError> {
    // Validate port format to prevent command injection via subprocess args
    if !PORT_RE.is_match(port) {
        return Err(AppError::CommandFailed(format!("Invalid port: {}", port)));
    }

    // Reject command strings containing PM3 command separators or newlines.
    // The PM3 CLI's `-c` flag treats `;` as a delimiter, so a crafted value
    // like "AA;lf t55xx wipe" would execute two commands. Block this at the
    // chokepoint so no caller can accidentally pass through unsanitised input.
    if cmd.contains(';') || cmd.contains('\n') || cmd.contains('\r') {
        return Err(AppError::CommandFailed(
            "Invalid characters in command".into(),
        ));
    }
    if port.contains(';') || port.contains('\n') || port.contains('\r') {
        return Err(AppError::CommandFailed(
            "Invalid characters in command".into(),
        ));
    }

    // 1) Try bundled sidecar binary first (available in production builds).
    //    In dev mode the sidecar won't exist, so this silently falls through.
    match try_sidecar_silent(app, port, cmd, wait).await {
        Ok(output) => return Ok(output),
        Err(_) => { /* sidecar not available -- fall through to PATH/scope lookup */ }
    }

    // 2) Fall back to PATH-based lookup, then common install locations.
    // Each scope name maps to a binary path registered in capabilities/default.json.
    let scope_names = pm3_scope_names();
    let mut first_spawn_error: Option<AppError> = None;

    for scope_name in &scope_names {
        let output_future = app
            .shell()
            .command(scope_name)
            .args(["-p", port, "-f", "-c", cmd])
            .output();

        // Note: When the timeout fires and the future is dropped, Tauri's shell plugin
        // handles cleanup of the child process. The `tokio::time::timeout` wrapper
        // ensures we don't wait forever, and the Tauri runtime drops the child on cancel.
        let output = match timeout(wait, output_future).await {
            Err(_) => {
                return Err(AppError::Timeout(format!(
                    "PM3 command timed out after {}s: {}",
                    wait.as_secs(),
                    cmd
                )));
            }
            Ok(Err(e)) => {
                // Spawn failed -- binary not found at this path. Record the error
                // from the first attempt (PATH lookup) and try the next location.
                if first_spawn_error.is_none() {
                    first_spawn_error = Some(AppError::CommandFailed(format!(
                        "Failed to spawn proxmark3: {}",
                        e
                    )));
                }
                continue;
            }
            Ok(Ok(output)) => output,
        };

        // Binary was found and executed -- process the result immediately.
        // No further fallback attempts needed regardless of exit code.
        let code = output.status.code().unwrap_or(-1);
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();

        return match code {
            0 => {
                let cleaned = strip_ansi(&stdout);
                // PM3 reports a command it does not recognise with exit code 0 and
                // prints either an argparse error or the whole help menu for the
                // command group. Treating that as success is what let
                // `lf t55xx set config` and `hf mf ejectblk` ship unnoticed: the
                // app rendered the help text as though it were a result.
                if let Some(reason) = rejected_command(&cleaned) {
                    return Err(AppError::CommandFailed(format!(
                        "PM3 rejected the command ({})",
                        reason
                    )));
                }
                if let Some(reason) = device_failure(&cleaned) {
                    return Err(AppError::CommandFailed(reason));
                }
                // PM3 signals "nothing found" inconsistently. `hf search`
                // exits -10, but `hf 14a info`, `hf mf info` and `hf mfu info`
                // exit 0 having printed only the connection banner. Those
                // reached the UI as a blank, success-looking result, which is
                // indistinguishable from the app being broken -- it made a
                // card sitting outside the coil look like a dead reader.
                if is_card_dependent(cmd) && is_banner_only(&cleaned) {
                    return Err(AppError::CommandFailed(format!(
                        "No tag detected running: {}. Place the card on the reader and try again.",
                        cmd
                    )));
                }
                Ok(cleaned)
            }
            -5 | 251 => Err(AppError::Timeout(format!("PM3 timed out running: {}", cmd))),
            _ => {
                // PM3 exits non-zero for "found something but could not classify
                // it" as well as for "found nothing". `lf search` on an
                // unconfigured T5577 prints "[+] Chipset... T55xx" and then exits
                // -10, so discarding stdout here loses a real detection. Only the
                // search callers opt in -- see the `tolerate_nonzero` docs above.
                let cleaned = strip_ansi(&stdout);
                if let Some(reason) = device_failure(&cleaned) {
                    return Err(AppError::CommandFailed(reason));
                }
                if tolerate_nonzero && !cleaned.trim().is_empty() {
                    return Ok(cleaned);
                }
                Err(AppError::CommandFailed(friendly_exit_code(code, cmd)))
            }
        };
    }

    // All scope names exhausted -- return the first spawn error (from PATH lookup)
    // so the error message is the most user-recognizable one.
    Err(first_spawn_error.unwrap_or_else(|| {
        AppError::CommandFailed("Failed to spawn proxmark3: binary not found".into())
    }))
}

/// Map PM3 exit codes to friendly messages.
/// PM3 uses negative codes for specific conditions — -2 is the most common
/// "no tag found" code across all tag types.
fn friendly_exit_code(code: i32, cmd: &str) -> String {
    match code {
        -2 => format!("No tag found running: {}", cmd),
        -3 => format!("Unknown option running: {}", cmd),
        -4 => format!("Invalid argument running: {}", cmd),
        -5 => format!("PM3 timed out running: {}", cmd),
        -7 => format!("No tag found running: {}", cmd),
        -10 => {
            // PM3 returns -10 ("Failed to identify tagtype") for a range of
            // conditions. For dump/emulate commands it usually means no key
            // file or no card on the reader — give the user something actionable.
            if cmd.contains("dump") || cmd.contains("efill") || cmd.contains("esave")
                || cmd.contains("sim") || cmd.contains("elock")
            {
                format!(
                    "No key file or no card on reader running: {}. Run 'hf mf autopwn' first to recover keys, or place the card on the reader.",
                    cmd
                )
            } else {
                format!("No tag found running: {}", cmd)
            }
        }
        251 => format!("PM3 timed out running: {}", cmd),
        // Codes below come from the `#define PM3_E*` list in `pm3_cmd.h`.
        -1 => format!("Undefined error running: {}", cmd),
        -6 => format!("Command not implemented in this client running: {}", cmd),
        -8 => format!("Communication error with the device running: {}", cmd),
        -11 => format!("Flash error running: {}", cmd),
        -13 => format!("File error (missing or unreadable) running: {}", cmd),
        -16 => format!("Wrong answer from the card running: {}", cmd),
        -18 => format!("Card exchange error running: {}", cmd),
        -20 => format!("APDU exchange failed running: {}. Is a card of the expected type on the reader?", cmd),
        -21 => format!("PM3 command failed running: {}", cmd),
        -22 => format!("Partial result only running: {}", cmd),
        -23 => format!("Card left the field (tear-off) running: {}", cmd),
        -24 => format!("CRC error running: {}", cmd),
        -25 => format!("Static nonce detected running: {}", cmd),
        -26 => format!("No PACS session running: {}", cmd),
        -27 => format!("Invalid length running: {}", cmd),
        -28 => format!("No key available running: {}", cmd),
        -29 => format!("Cryptographic error running: {}", cmd),
        -30 => format!("No such file running: {}", cmd),
        -98 => format!("No data available running: {}", cmd),
        -99 => format!("Fatal error running: {}", cmd),
        _ => format!("Exit code {}: {}", code, cmd),
    }
}

/// True for commands that interrogate a tag and therefore can only report
/// "nothing here" rather than failing.
///
/// Deliberately limited to the `hf` and `lf` command groups. Device-level
/// commands such as `hw version` are excluded because a silent success is
/// normal for some of them, and turning that into an error would be wrong.
fn is_card_dependent(cmd: &str) -> bool {
    let c = cmd.trim_start();
    c.starts_with("hf ") || c.starts_with("lf ") || c == "hf" || c == "lf"
}

/// True when PM3's output is nothing but the per-invocation connection banner.
///
/// Verbatim output of `hf mf info` with no card on the reader, exit code 0:
/// ```text
/// [=] Session log .../log_20260930155332.txt
/// [+] loaded `.../preferences.json`
/// [+] execute command from commandline: hf mf info
/// [+] Using UART port COM19
/// [+] Communicating with PM3 over USB-CDC
/// [+] Max frame size: 624 bytes
/// [+] Emulator memory: 8192 bytes
/// [usb|script] pm3 --> hf mf info
/// ```
/// Nothing after that means no tag answered.
fn is_banner_only(output: &str) -> bool {
    output.lines().all(|line| {
        let clean = strip_ansi(line);
        let t = clean.trim();
        t.is_empty()
            || t.starts_with("[=] Session log")
            || t.starts_with("[+] loaded `")
            || t.starts_with("[+] execute command from commandline:")
            || t.starts_with("[+] Using UART port")
            || t.starts_with("[+] Communicating with PM3")
            || t.starts_with("[+] Max frame size")
            || t.starts_with("[+] Emulator memory")
            || t.starts_with("[usb|script] pm3 -->")
    })
}

/// Run a single PM3 command: spawns `proxmark3 -p {port} -f -c "{cmd}"`,
/// waits for the process to exit (with a 30-second timeout), then returns cleaned stdout.
/// If the subprocess hangs (e.g., USB cable pulled), it will be killed after the timeout.
///
/// Emits the command being run and its output to the frontend terminal panel.
///
/// **Known limitation -- subprocess cancellation on reset:**
/// This function uses `tauri_plugin_shell`'s `.output()` which internally spawns a child
/// process and collects stdout/stderr until exit. Because the child handle is owned by the
/// shell plugin's future and not exposed to callers, we cannot kill the subprocess from
/// outside (e.g., when the user presses Reset during a write operation). Refactoring to
/// `spawn()` + async stream reading would be needed for true cancellation support.
///
/// In practice this is acceptable because:
/// - T5577/EM4305 LF writes complete in under 2 seconds.
/// - The 30-second timeout (`PM3_COMMAND_TIMEOUT`) already protects against hangs.
/// - When the Tauri future is dropped (timeout or app shutdown), the shell plugin
///   cleans up the child process.
pub async fn run_command(app: &AppHandle, port: &str, cmd: &str) -> Result<String, AppError> {
    // Dictionary attacks run for minutes, not seconds. Give them their own
    // budget so the PM3 child is never killed mid-run holding COM24.
    let wait = if is_long_running(cmd) {
        LONG_COMMAND_TIMEOUT
    } else {
        PM3_COMMAND_TIMEOUT
    };
    emit_output(app, &format!("pm3 --> {}", cmd), false);
    match execute_pm3(app, port, cmd, wait, false).await {
        Ok(output) => {
            emit_output(app, &output, false);
            Ok(output)
        }
        Err(e) => {
            emit_output(app, &e.to_string(), true);
            Err(e)
        }
    }
}

/// True for the brute-force / dictionary-attack commands that legitimately run
/// for minutes. `lf t55xx chk` measured 26.8s against the 30s
/// `PM3_COMMAND_TIMEOUT`, so it was being killed mid-run and the aborted child
/// held the serial port — the user saw "invalid serial port" instead of a
/// result. Matched on a subcommand boundary so a longer dictionary is not
/// required for the check to keep working.
fn is_long_running(cmd: &str) -> bool {
    const LONG: &[&str] = &[
        "lf t55xx chk",
        "lf t55xx bruteforce",
        "lf t55xx brute",
        "lf hid bruteforce",
        "lf em bruteforce",
        "hf 15 bruteforce",
        "hf 15 brute",
        "hf mf bruteforce",
        "hf mf brute",
        "hf mfu desbrute",
        "hf mfdes chk",
        "hf mfdes bruteaid",
        "hf mfdes bruteisofid",
        "hf mfdes brutedamslot",
    ];
    LONG.iter().any(|l| {
        // Require the match to end at a boundary so "lf t55xx chk" does not
        // accidentally match a longer command, and so we do not match
        // "lf t55xx chkpwds-style" prefixes by accident.
        cmd == *l || cmd.strip_prefix(l).is_some_and(|rest| rest.starts_with(' '))
    })
}

/// Run a tag-detection command with a shorter timeout (8s).
/// PM3 hangs when no tag of the requested type is on the reader — e.g.
/// `hf 14b info` with no 14B card present. A 30s wait per panel click is
/// unacceptable. Most info commands either succeed in 1-2s or fail fast.
/// Returns the cleaned output, or an AppError::Timeout if the process hangs.
pub async fn run_command_quick(
    app: &AppHandle,
    port: &str,
    cmd: &str,
) -> Result<String, AppError> {
    emit_output(app, &format!("pm3 --> {} (quick)", cmd), false);
    match execute_pm3(app, port, cmd, DETECT_COMMAND_TIMEOUT, false).await {
        Ok(output) => {
            emit_output(app, &output, false);
            Ok(output)
        }
        Err(e) => {
            let friendly = if let AppError::Timeout(_) = &e {
                // PM3 hung because no tag of the requested type is on the reader.
                // Return a clean message instead of a raw timeout.
                AppError::CommandFailed(format!(
                    "No {} tag found on the reader.",
                    detect_tag_type(cmd)
                ))
            } else {
                e
            };
            emit_output(app, &friendly.to_string(), true);
            Err(friendly)
        }
    }
}

/// Run a card-search command (`lf search`, `hf search`) and return the output
/// even when PM3 exits non-zero.
///
/// PM3 signals "found something but could not classify it" with a non-zero exit
/// code while still printing the detection. `lf search` on a T5577 emits
/// `[-] No known 125/134 kHz tags found!`, then `[+] Chipset... T55xx`, then
/// exits -10. The strict `run_command` path discards stdout on any non-zero
/// exit, so the scan wizard saw an error and reported "Scan failed" for a card
/// that was sitting on the antenna.
///
/// The output parser is the authority on whether a card was actually found, so
/// hand it everything and let it decide. Spawn failures and timeouts still
/// return `Err` — only the exit-code handling is relaxed.
pub async fn run_search_command(
    app: &AppHandle,
    port: &str,
    cmd: &str,
) -> Result<String, AppError> {
    emit_output(app, &format!("pm3 --> {}", cmd), false);
    // SEARCH_COMMAND_TIMEOUT, not DETECT_COMMAND_TIMEOUT: `lf search` and
    // `hf search` are full-spectrum sweeps that legitimately take ~11s.
    match execute_pm3(app, port, cmd, SEARCH_COMMAND_TIMEOUT, true).await {
        Ok(output) => {
            emit_output(app, &output, false);
            Ok(output)
        }
        Err(e) => {
            emit_output(app, &e.to_string(), true);
            Err(e)
        }
    }
}

/// Detect PM3 output that means "I do not have that command", as opposed to a
/// command that ran and found nothing.
///
/// Both shapes exit 0, so the exit code alone cannot tell them apart:
///
///   lf t55xx danger raw
///   lf t55xx dangerraw: unexpected argument "raw"
///   [!] Try 'lf t55xx dangerraw --help' for more information.
///
///   lf t55xx set config
///   --------- operations ----------
///   config      Set/Get T55XX configuration ...
///
/// The second form is an unknown *subcommand*: PM3 falls back to the help menu
/// for the group. Section banners like `----- operations -----` only appear in
/// that menu, so they are a reliable marker.
fn rejected_command(cleaned: &str) -> Option<&'static str> {
    if cleaned.contains("unexpected argument \"") {
        return Some("unknown option or argument");
    }
    if cleaned.contains("for more information.") && cleaned.contains("--help'") {
        return Some("command not recognised");
    }
    if HELP_BANNER_RE.is_match(cleaned) {
        return Some("unknown subcommand, help menu printed instead");
    }
    None
}

static HELP_BANNER_RE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"-{5,}\s*(operations|recovery|simulation|notice|technical|magic gen|general)\s*-{5,}")
        .expect("bad help banner regex")
});

/// Detect PM3 output that means the command never reached the device.
///
/// Without this, a dropped USB connection looks exactly like an empty antenna.
/// `run_search_command` sets `tolerate_nonzero`, and PM3 exits 1 on a port
/// failure while still printing several non-empty lines, so the port error was
/// returned as a successful result. The parser then found no card in it and the
/// wizard told the user to place a card that was already on the reader.
///
/// Checked on both the exit-0 and the tolerated non-zero paths, so it is
/// independent of `tolerate_nonzero`.
/// Append PM3's own error text to a friendly message.
///
/// `friendly_exit_code` produces the short human summary, but it discards what
/// PM3 actually printed. That text is the only thing that distinguishes, for
/// example, an unreadable card from a missing key file. Keep the summary first
/// so existing wording stays intact, and only append when PM3 said something
/// that is not just its own echo of the command.
fn with_detail(message: String, detail: &str) -> String {
    let detail = detail.trim();
    // Drop the "execute command from commandline:" preamble and blank lines; keep
    // the informative remainder.
    let useful = detail
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with("[+] execute command from commandline"))
        .collect::<Vec<_>>()
        .join(" ");
    if useful.is_empty() {
        message
    } else {
        format!("{} ({})", message, useful)
    }
}

fn device_failure(cleaned: &str) -> Option<String> {
    const MARKERS: &[&str] = &[
        "invalid serial port",
        "error opening serial port",
        "failed to open the serial port",
        "cannot open the port",
        "could not open port",
        "permission denied",
    ];
    // PM3's wording differs across platforms and versions ("Cannot open the
    // port" vs "cannot open the port"), so match case-insensitively.
    let lower = cleaned.to_lowercase();
    for marker in MARKERS {
        if lower.contains(marker) {
            return Some(format!(
                "Proxmark3 could not open the serial port ({}). Reconnect the device and try again.",
                marker
            ));
        }
    }
    None
}

/// Heuristic: extract the tag type from a PM3 info command so the error
/// message can say "No 14B tag found" instead of just "timed out".
fn detect_tag_type(cmd: &str) -> &str {    if cmd.contains("14b") { "ISO 14443-B" }
    else if cmd.contains("14a") { "ISO 14443-A" }
    else if cmd.contains("15") { "ISO 15693" }
    else if cmd.contains("felica") { "Felica" }
    else if cmd.contains("iclass") { "iCLASS" }
    else if cmd.contains("legic") { "LEGIC" }
    else if cmd.contains("mfu") { "MIFARE Ultralight" }
    else if cmd.contains("mfdes") { "DESFire" }
    else if cmd.contains("calypso") { "Calypso" }
    else if cmd.contains("emrtd") { "eMRTD passport" }
    else if cmd.contains("t55") { "T55xx" }
    else if cmd.contains("em4305") { "EM4305" }
    else if cmd.contains("trovan") { "Trovan" }
    else { "requested" }
}

// ---------------------------------------------------------------------------
// HF Operation State — holds child process for cancellation + dump file path
// ---------------------------------------------------------------------------

/// Managed state for long-running HF operations (autopwn, dump, write).
/// Stored via `app.manage()` in `lib.rs`.
pub struct HfOperationState {
    /// Running child process — `take()` to kill via `CommandChild::kill(self)`.
    pub child: Mutex<Option<CommandChild>>,
    /// Dump file path set by autopwn after completion (e.g. "hf-mf-01020304-dump.bin").
    pub dump_path: Mutex<Option<String>>,
}

impl HfOperationState {
    pub fn new() -> Self {
        Self {
            child: Mutex::new(None),
            dump_path: Mutex::new(None),
        }
    }
}

// ---------------------------------------------------------------------------
// Streaming command execution (HF operations)
// ---------------------------------------------------------------------------

/// Run a PM3 command with streaming output, supporting long timeouts and
/// cancellation. Unlike `run_command()` which uses `.output()` (blocks until
/// exit), this uses `.spawn()` + async line reading.
///
/// - Each stdout/stderr line is emitted as a `pm3-output` event (live terminal).
/// - A per-line callback `on_line` is invoked for real-time parsing (e.g. autopwn
///   progress events). The callback receives the cleaned line text.
/// - The child process is stored in `hf_state.child` so `cancel_hf_operation`
///   can kill it mid-run.
/// - Returns the accumulated cleaned output on success.
pub async fn run_command_streaming<F>(
    app: &AppHandle,
    port: &str,
    cmd: &str,
    timeout_secs: u64,
    hf_state: &HfOperationState,
    mut on_line: F,
) -> Result<String, AppError>
where
    F: FnMut(&str),
{
    // Validate port
    if !PORT_RE.is_match(port) {
        return Err(AppError::CommandFailed(format!("Invalid port: {}", port)));
    }

    // Reject command separators
    if cmd.contains(';') || cmd.contains('\n') || cmd.contains('\r') {
        return Err(AppError::CommandFailed(
            "Invalid characters in command".into(),
        ));
    }

    emit_output(app, &format!("pm3 --> {}", cmd), false);

    // Try sidecar first, then scope names — same strategy as execute_pm3()
    let (rx, child) = spawn_pm3(app, port, cmd)?;

    // Store child for cancellation
    {
        let mut lock = hf_state
            .child
            .lock()
            .map_err(|e| AppError::CommandFailed(format!("HF state lock poisoned: {}", e)))?;
        *lock = Some(child);
    }

    // Read lines with timeout
    let result = read_stream_with_timeout(app, rx, timeout_secs, &mut on_line).await;

    // Clear child on completion (process already exited or was killed)
    {
        let mut lock = hf_state.child.lock().unwrap_or_else(|e| e.into_inner());
        *lock = None;
    }

    match result {
        Ok(output) => Ok(output),
        Err(e) => {
            emit_output(app, &e.to_string(), true);
            Err(e)
        }
    }
}

/// Spawn PM3 via sidecar or scope names, returning the event receiver + child.
fn spawn_pm3(
    app: &AppHandle,
    port: &str,
    cmd: &str,
) -> Result<(tauri::async_runtime::Receiver<CommandEvent>, CommandChild), AppError> {
    let args = ["-p", port, "-f", "-c", cmd];

    // Try direct binary spawn first (Tauri's externalBin places binary in same dir as executable)
    // This uses std::process::Command with CREATE_NO_WINDOW to suppress console popups
    if let Some(exe_path) = std::env::current_exe().ok() {
        if let Some(dir) = exe_path.parent() {
            let exe_name = if cfg!(target_os = "windows") {
                "proxmark3.exe"
            } else {
                "proxmark3"
            };

            // Try same directory as executable (Tauri externalBin typical behavior)
            let binary_path = dir.join(exe_name);
            if binary_path.is_file() {
                let binary_str = binary_path.to_string_lossy().into_owned();
                #[cfg(target_os = "windows")]
                {
                    match app.shell().command(&binary_str).args(&args).spawn() {
                        Ok(result) => return Ok(result),
                        Err(_) => {}
                    }
                }
                #[cfg(not(target_os = "windows"))]
                {
                    match app.shell().command(&binary_str).args(&args).spawn() {
                        Ok(result) => return Ok(result),
                        Err(_) => {}
                    }
                }
            }
        }
    }

    // Try sidecar (available in production builds)
    #[cfg(target_os = "windows")]
    {
        if let Ok(sidecar_cmd) = app.shell().sidecar("binaries/proxmark3") {
            if let Ok(result) = sidecar_cmd.args(&args).spawn() {
                return Ok(result);
            }
        }
    }

    #[cfg(not(target_os = "windows"))]
    {
        if let Ok(sidecar_cmd) = app.shell().sidecar("binaries/proxmark3") {
            if let Ok(result) = sidecar_cmd.args(&args).spawn() {
                return Ok(result);
            }
        }
    }

    // Fall back to scope names
    let scope_names = pm3_scope_names();
    let mut first_err: Option<String> = None;

    for scope_name in &scope_names {
        match app.shell().command(scope_name).args(&args).spawn() {
            Ok(result) => return Ok(result),
            Err(e) => {
                if first_err.is_none() {
                    first_err = Some(format!("{}", e));
                }
            }
        }
    }

    Err(AppError::CommandFailed(format!(
        "Failed to spawn proxmark3: {}",
        first_err.unwrap_or_else(|| "binary not found".into())
    )))
}

/// Read from a `CommandEvent` receiver, accumulating output and emitting lines.
/// Returns the full cleaned output when the process terminates.
async fn read_stream_with_timeout<F>(
    app: &AppHandle,
    mut rx: tauri::async_runtime::Receiver<CommandEvent>,
    timeout_secs: u64,
    on_line: &mut F,
) -> Result<String, AppError>
where
    F: FnMut(&str),
{
    let deadline = Duration::from_secs(timeout_secs);
    let mut accumulated = String::new();
    let mut exit_code: Option<i32> = None;

    loop {
        match timeout(deadline, rx.recv()).await {
            Err(_) => {
                // Timeout expired
                return Err(AppError::Timeout(format!(
                    "HF operation timed out after {}s",
                    timeout_secs
                )));
            }
            Ok(None) => {
                // Channel closed — process exited
                break;
            }
            Ok(Some(event)) => match event {
                CommandEvent::Stdout(bytes) => {
                    let line = String::from_utf8_lossy(&bytes);
                    let cleaned = strip_ansi(&line);
                    let trimmed = cleaned.trim();
                    if !trimmed.is_empty() {
                        emit_output(app, trimmed, false);
                        on_line(trimmed);
                        accumulated.push_str(trimmed);
                        accumulated.push('\n');
                    }
                }
                CommandEvent::Stderr(bytes) => {
                    let line = String::from_utf8_lossy(&bytes);
                    let cleaned = strip_ansi(&line);
                    let trimmed = cleaned.trim();
                    if !trimmed.is_empty() {
                        emit_output(app, trimmed, true);
                        on_line(trimmed);
                        accumulated.push_str(trimmed);
                        accumulated.push('\n');
                    }
                }
                CommandEvent::Error(msg) => {
                    emit_output(app, &msg, true);
                    return Err(AppError::CommandFailed(format!("Process error: {}", msg)));
                }
                CommandEvent::Terminated(payload) => {
                    exit_code = payload.code;
                    break;
                }
                _ => {} // Future CommandEvent variants — ignore
            },
        }
    }

    // Check exit code
    match exit_code {
        Some(0) | None => Ok(accumulated),
        Some(-5) | Some(251) => Err(AppError::Timeout("PM3 subprocess timed out".into())),
        Some(code) => Err(AppError::CommandFailed(format!(
            "PM3 exited with code {}",
            code
        ))),
    }
}

/// Scan common COM/serial ports trying `hw version` to find a connected PM3.
/// Returns (port, model, firmware) on success.
///
/// Uses friendly, hacker-casual terminal output. All probe messages are green
/// (non-error) except the final "not found" message.
///
/// Each port is probed with a short 3-second timeout (DETECT_TIMEOUT) so that
/// scanning 40 COM ports completes in under 2 minutes even when most ports
/// are empty. A real PM3 responds to `hw version` in well under 2 seconds.
pub async fn detect_device(app: &AppHandle) -> Result<(String, String, String), AppError> {
    let candidates = build_port_candidates();

    // Pick a random init message for personality
    let init_msgs = [
        "[=] Sniffing USB bus... come out, Proxmark",
        "[=] Deploying port tentacles...",
        "[=] Hunting for hardware... stay still",
        "[=] Scanning the wire... don't be shy",
        "[=] Reaching out to the other side...",
    ];
    let idx = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos() as usize
        % init_msgs.len();
    emit_output(app, init_msgs[idx], false);

    for port in &candidates {
        emit_output(app, &format!("[=] Knocking on {}...", port), false);

        match probe_port(app, port).await {
            Ok(output) => {
                if let Some((model, firmware)) = parse_hw_version(&output) {
                    emit_output(
                        app,
                        &format!("[+] Target acquired: {} on {}", model, port),
                        false,
                    );
                    emit_output(app, &format!("[+] Firmware: {}", firmware), false);
                    return Ok((port.clone(), model, firmware));
                }
                // Got output but couldn't parse hw version -- wrong device
                emit_output(app, &format!("[-] {} -- wrong device", port), false);
            }
            Err(e) => {
                // Capabilities mismatch means the PM3 device IS present on this
                // port but the firmware doesn't match the client version. Treat
                // it as a successful detection -- the firmware check step will
                // handle the mismatch and offer to flash.
                let err_msg = e.to_string();
                if err_msg.to_lowercase().contains("capabilities") {
                    emit_output(
                        app,
                        &format!(
                            "[+] Target acquired: Proxmark3 on {} (firmware mismatch)",
                            port
                        ),
                        false,
                    );
                    return Ok((
                        port.clone(),
                        "Proxmark3".to_string(),
                        "mismatched".to_string(),
                    ));
                }

                // Distinguish "no response" (spawn succeeded but device didn't respond)
                // from other errors. If spawn itself failed (binary not found), that
                // affects ALL ports, so propagate immediately.
                if err_msg.contains("Failed to spawn proxmark3") {
                    emit_output(
                        app,
                        "[!!] Proxmark3 binary not found. Check installation.",
                        true,
                    );
                    return Err(e);
                }

                emit_output(app, &format!("[-] {} -- no response", port), false);
            }
        }
    }

    emit_output(app, "[!!] No Proxmark3 found.", true);
    emit_output(
        app,
        "[=] Try a different USB cable (some are charge-only)",
        false,
    );
    emit_output(app, "[=] Check Device Manager for a COM port", false);
    emit_output(
        app,
        "[=] PM3 Easy: may need CH340 driver (wch-ic.com)",
        false,
    );
    Err(AppError::DeviceNotFound)
}

/// Probe a single port with a short timeout for device detection.
/// Uses DETECT_TIMEOUT (3s) instead of the full PM3_COMMAND_TIMEOUT (30s)
/// so scanning 40 COM ports completes quickly.
async fn probe_port(app: &AppHandle, port: &str) -> Result<String, AppError> {
    let scope_names = pm3_scope_names();
    let mut first_spawn_error: Option<AppError> = None;

    for scope_name in &scope_names {
        let output_future = app
            .shell()
            .command(scope_name)
            .args(["-p", port, "-f", "-c", "hw version"])
            .output();

        let output = match timeout(DETECT_TIMEOUT, output_future).await {
            Err(_) => {
                // Port timed out -- likely no device. Skip to next port.
                return Err(AppError::Timeout(format!(
                    "Port {} timed out during detection",
                    port
                )));
            }
            Ok(Err(e)) => {
                // Spawn failed -- binary not found at this path. Record the error
                // from the first attempt (PATH lookup) and try the next location.
                if first_spawn_error.is_none() {
                    first_spawn_error = Some(AppError::CommandFailed(format!(
                        "Failed to spawn proxmark3: {}",
                        e
                    )));
                }
                continue;
            }
            Ok(Ok(output)) => output,
        };

        // Binary was found and executed -- process the result immediately.
        let code = output.status.code().unwrap_or(-1);
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        return match code {
            0 => {
                let cleaned = strip_ansi(&stdout);
                Ok(cleaned)
            }
            -5 | 251 => Err(AppError::Timeout(format!("PM3 timed out running: {}", "hw version"))),
            _ => {
                let detail = if stderr.is_empty() {
                    strip_ansi(&stdout)
                } else {
                    strip_ansi(&stderr)
                };
                Err(AppError::CommandFailed(with_detail(
                    friendly_exit_code(code, "hw version"),
                    &detail,
                )))
            }
        };
    }

    // All scope names exhausted -- return the first spawn error (from PATH lookup)
    // so the error message is the most user-recognizable one.
    Err(first_spawn_error.unwrap_or_else(|| {
        AppError::CommandFailed("Failed to spawn proxmark3: binary not found".into())
    }))
}

fn build_port_candidates() -> Vec<String> {
    // Get available ports from serialport and score them
    let mut scored = Vec::new();

    if let Ok(available) = serialport::available_ports() {
        for info in available {
            let port_str = info.port_name.clone();
            let score = score_port(&port_str, &info.port_type);
            scored.push((score, port_str));
        }
    }

    // If serialport couldn't list ports (or returned none), fall back to static list
    if scored.is_empty() {
        scored = build_fallback_candidates();
    }

    // Sort by score descending (highest score first)
    scored.sort_by(|a, b| b.0.cmp(&a.0));

    scored.into_iter().map(|(_, port)| port).collect()
}

/// Score a port based on heuristics: prefer ACM over USB on Linux,
/// lower-numbered COM ports on Windows, and known PM3 suffixes on macOS.
fn score_port(port_name: &str, port_type: &serialport::SerialPortType) -> u32 {
    let mut score: u32 = 0;

    // Base score
    score += 10;

    // Platform-specific scoring
    #[cfg(target_os = "linux")]
    {
        // Prefer ttyACM (built-in USB-serial) over ttyUSB (external adapters)
        if port_name.contains("ttyACM") {
            score += 50;
        } else if port_name.contains("ttyUSB") {
            score += 20;
        }
    }

    #[cfg(target_os = "windows")]
    {
        // Prefer lower COM port numbers (more common for PM3 devices)
        if let Some(num) = port_name.strip_prefix("COM") {
            if let Ok(n) = num.parse::<u32>() {
                score += 50;
                // Lower numbers get higher scores
                if n <= 10 {
                    score += 30;
                }
            }
        }
    }

    #[cfg(target_os = "macos")]
    {
        // Prefer known PM3 suffixes
        let pm3_suffixes = ["iceman1", "14101", "14201", "14301"];
        for suffix in pm3_suffixes {
            if port_name.contains(suffix) {
                score += 50;
                break;
            }
        }
    }

    // Check port type if available
    if let serialport::SerialPortType::UsbPort(info) = port_type {
        // Award points for vendor/product IDs that match known PM3 devices
        let known_vendors = [0x0403, 0x10C4, 0x03EB]; // FTDI, SiLabs, Atmel
        if known_vendors.contains(&info.vid) {
            score += 30;
        }
    }

    score
}

/// Build fallback port list when serialport enumeration fails.
fn build_fallback_candidates() -> Vec<(u32, String)> {
    let mut ports = Vec::new();

    if cfg!(target_os = "windows") {
        // Windows COM ports -- extend to 40 to cover USB hub reassignment
        for i in 1..=40 {
            ports.push((20, format!("COM{}", i)));
        }
    } else if cfg!(target_os = "macos") {
        // macOS: /dev/tty.usbmodem* -- cover common PM3 suffixes
        for suffix in &["iceman1", "14101", "14201", "14301", "1", "2", "3"] {
            ports.push((30, format!("/dev/tty.usbmodem{}", suffix)));
        }
    } else {
        // Linux: /dev/ttyACM* and /dev/ttyUSB*
        for i in 0..=5 {
            ports.push((50, format!("/dev/ttyACM{}", i)));
            ports.push((20, format!("/dev/ttyUSB{}", i)));
        }
    }

    ports
}

/// Run the proxmark3 binary directly using tokio::process::Command.
/// Used for bundled binaries found via current_exe() lookup.
///
/// `wait` controls how long to wait for the subprocess. Pass
/// `PM3_COMMAND_TIMEOUT` (30s) for normal commands and `DETECT_COMMAND_TIMEOUT`
/// (8s) for tag-detection commands where PM3 hangs when no tag is present.
async fn run_binary_direct(
    binary_path: std::path::PathBuf,
    port: &str,
    cmd: &str,
    wait: Duration,
) -> Result<String, AppError> {
    // On Windows, use std::process::Command with CREATE_NO_WINDOW to suppress console popups
    // tokio's Command doesn't expose creation_flags, so we use std::process and wrap for async
    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x08000000;
        
        let mut std_command = std::process::Command::new(&binary_path);
        std_command.args(&["-p", port, "-f", "-c", cmd]);
        std_command.creation_flags(CREATE_NO_WINDOW);
        std_command.stdout(std::process::Stdio::piped());
        std_command.stderr(std::process::Stdio::piped());

        // Use tokio to wrap the sync command output.
        //
        // kill_on_drop is essential, not an optimisation. When the timeout below
        // fires, the future is dropped -- and tokio's default is kill_on_drop =
        // false, which ORPHANS the PM3 child. The orphan keeps the serial port
        // open, so the very next command fails with "invalid serial port".
        // Measured on this device: `lf search` takes ~10s, so any cap below that
        // produced a self-inflicted cascade of port errors.
        let output_future = tokio::process::Command::from(std_command)
            .kill_on_drop(true)
            .output();
        let output = match timeout(wait, output_future).await {
            Err(_) => {
                return Err(AppError::Timeout(format!(
                    "PM3 command timed out after {}s: {}",
                    wait.as_secs(),
                    cmd
                )));
            }
            Ok(Ok(output)) => output,
            Ok(Err(e)) => {
                return Err(AppError::CommandFailed(format!(
                    "Failed to run PM3 command: {}",
                    e
                )));
            }
        };

        let code = output.status.code().unwrap_or(-1);
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        match code {
            0 => {
                let cleaned = strip_ansi(&stdout);
                if let Some(reason) = device_failure(&cleaned) {
                    return Err(AppError::CommandFailed(reason));
                }
                Ok(cleaned)
            }
            -5 | 251 => Err(AppError::Timeout(format!("PM3 timed out running: {}", cmd))),
            _ => {
                let detail = if stderr.is_empty() {
                    strip_ansi(&stdout)
                } else {
                    strip_ansi(&stderr)
                };
                Err(AppError::CommandFailed(with_detail(
                    friendly_exit_code(code, cmd),
                    &detail,
                )))
            }
        }
    }
    
    #[cfg(not(target_os = "windows"))]
    {
        let mut command = tokio::process::Command::new(binary_path);
        command.args(&["-p", port, "-f", "-c", cmd]);
        // See the Windows branch above: without this a timed-out PM3 child is
        // orphaned and keeps holding the serial port.
        command.kill_on_drop(true);

        let output_future = command.output();
        let output = match timeout(wait, output_future).await {
            Err(_) => {
                return Err(AppError::Timeout(format!(
                    "PM3 command timed out after {}s: {}",
                    wait.as_secs(),
                    cmd
                )));
            }
            Ok(Ok(output)) => output,
            Ok(Err(e)) => {
                return Err(AppError::CommandFailed(format!(
                    "Failed to run PM3 command: {}",
                    e
                )));
            }
        };

        let code = output.status.code().unwrap_or(-1);
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        match code {
            0 => {
                let cleaned = strip_ansi(&stdout);
                Ok(cleaned)
            }
            -5 | 251 => Err(AppError::Timeout(format!("PM3 timed out running: {}", cmd))),
            _ => {
                let detail = if stderr.is_empty() {
                    strip_ansi(&stdout)
                } else {
                    strip_ansi(&stderr)
                };
                Err(AppError::CommandFailed(with_detail(
                    friendly_exit_code(code, cmd),
                    &detail,
                )))
            }
        }
    }
}

/// Attempting to run a PM3 command via the bundled sidecar binary (silent -- no emit).
/// Returns Ok(stdout) on success, Err on any failure (sidecar not found, spawn
/// error, non-zero exit code). Callers should fall through to PATH-based lookup
/// on failure.
///
/// The sidecar binary depends on DLLs (Qt5, ICU, etc.) bundled in the same
/// directory via `bundle.resources`. The Windows DLL loader finds them
/// automatically since they share the sidecar's directory.
///
/// `wait` controls how long to wait for the subprocess.
async fn try_sidecar_silent(
    app: &AppHandle,
    port: &str,
    cmd: &str,
    wait: Duration,
) -> Result<String, AppError> {
    use std::env;

    // First, try to find the proxmark3 binary in the root directory (where DLLs are)
    // This matches Tauri's externalBin behavior where the binary is placed in the root
    if let Some(exe_path) = env::current_exe().ok() {
        let exe_dir = exe_path.parent();
        if let Some(dir) = exe_dir {
            let exe_name = if cfg!(target_os = "windows") {
                "proxmark3.exe"
            } else {
                "proxmark3"
            };

            // Try root directory first (DLLs are here)
            let root_path = dir.join(exe_name);
            if root_path.is_file() {
                return run_binary_direct(root_path, port, cmd, wait).await;
            }

            // Try binaries subdirectory (alternative config)
            let binary_path = dir.join("binaries").join(exe_name);
            if binary_path.is_file() {
                return run_binary_direct(binary_path, port, cmd, wait).await;
            }
        }
    }

    // Fall back to Tauri sidecar lookup for dev mode or bundled apps
    let sidecar = app
        .shell()
        .sidecar("binaries/proxmark3")
        .map_err(|e| AppError::CommandFailed(format!("Sidecar not available: {}", e)))?;

    let output_future = sidecar.args(["-p", port, "-f", "-c", cmd]).output();

let output = match timeout(wait, output_future).await {
            Err(_) => {
                return Err(AppError::Timeout(format!(
                    "PM3 command timed out after {}s: {}",
                    wait.as_secs(),
                    cmd
                )));
            }
        Ok(Err(e)) => {
            return Err(AppError::CommandFailed(format!(
                "Failed to run sidecar: {}",
                e
            )));
        }
        Ok(Ok(output)) => output,
    };

        let code = output.status.code().unwrap_or(-1);
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

    match code {
        0 => {
            let cleaned = strip_ansi(&stdout);
            Ok(cleaned)
        }
        -5 | 251 => Err(AppError::Timeout(format!("PM3 timed out running: {}", cmd))),
        _ => {
            let detail = if stderr.is_empty() {
                strip_ansi(&stdout)
            } else {
                strip_ansi(&stderr)
            };
            Err(AppError::CommandFailed(with_detail(
                friendly_exit_code(code, cmd),
                &detail,
            )))
        }
    }
}

fn parse_hw_version(output: &str) -> Option<(String, String)> {
    use crate::pm3::version::parse_detailed_hw_version;

    let info = parse_detailed_hw_version(output);

    // Pick best version source: os_version (device firmware) > client_version
    let version_str = if !info.os_version.is_empty() {
        info.os_version
    } else if !info.client_version.is_empty() {
        info.client_version
    } else {
        // No version found — check if it's at least a PM3 device
        if output.to_lowercase().contains("proxmark") {
            return Some((info.model, "unknown".to_string()));
        }
        return None;
    };

    // Extract clean short version like "v4.20728" for sidebar display
    let firmware = extract_short_version(&version_str);
    Some((info.model, firmware))
}

/// Extract a short version string like "v4.20728" from a full version string
/// like "Iceman/master/v4.20728-358-ga2ba91043-suspect".
fn extract_short_version(version_str: &str) -> String {
    // Find 'v' followed by a digit
    let v_pos = version_str.char_indices().find(|&(i, c)| {
        c == 'v'
            && version_str.get(i + 1..i + 2).map_or(false, |s| {
                s.as_bytes().first().map_or(false, |b| b.is_ascii_digit())
            })
    });

    if let Some((pos, _)) = v_pos {
        let rest = &version_str[pos..];
        // Version is "v" + digits/dots, stop at anything else
        let end = rest
            .find(|c: char| c != 'v' && !c.is_ascii_digit() && c != '.')
            .unwrap_or(rest.len());
        rest[..end].to_string()
    } else {
        version_str.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::{is_banner_only, is_card_dependent, rejected_command};

    /// Verbatim PM3 output for `lf t55xx danger raw`. Exit code 0.
    #[test]
    fn flags_unexpected_argument() {
        let out = "pm3 --> lf t55xx danger raw\n\
                   lf t55xx dangerraw: unexpected argument \"raw\"\n\
                   [!] Try 'lf t55xx dangerraw --help' for more information.\n";
        assert!(rejected_command(out).is_some());
    }

    /// Verbatim PM3 output for `lf t55xx chk pwds`. Exit code 0.
    #[test]
    fn flags_unknown_chk_subcommand() {
        let out = "lf t55xx chk: unexpected argument \"pwds\"\n";
        assert!(rejected_command(out).is_some());
    }

    /// Verbatim PM3 output for `hf mf ejectblk --blk 0`: the whole `hf mf`
    /// menu, exit code 0. Must not be reported as a successful command.
    #[test]
    fn flags_help_menu_instead_of_command() {
        let out = "help             This help\n\
                   list             List MIFARE history\n\
                   -----------      ----------------------- recovery ---------------\n\
                   darkside         Darkside attack\n\
                   -----------      ----------------------- operations --------------\n\
dump             Dump MIFARE Classic tag to binary file\n";
        assert!(rejected_command(out).is_some());
    }

    // -- banner-only detection (empty output means "no tag") ----------------

    /// Verbatim `hf mf info` output with no card on the reader. Exit code 0,
    /// and nothing beyond the connection banner. Real capture, COM19.
    const BANNER_ONLY: &str = "[=] Session log C:/tmp/.proxmark3/logs/log_20260930155332.txt\n\
[+] execute command from commandline: hf mf info\n\
\n\
[+] Using UART port COM19\n\
[+] Communicating with PM3 over USB-CDC\n\
[+] Max frame size: 624 bytes\n\
[+] Emulator memory: 8192 bytes\n\
[usb|script] pm3 --> hf mf info\n";

    #[test]
    fn banner_only_is_detected() {
        assert!(is_banner_only(BANNER_ONLY));
    }

    #[test]
    fn banner_only_tolerates_empty_output() {
        assert!(is_banner_only(""));
        assert!(is_banner_only("\n\n"));
    }

    /// A real result must not be mistaken for "no tag". Taken from
    /// logs/1247.md, the MIFARE Classic 1K detection.
    #[test]
    fn real_detection_is_not_banner_only() {
        let out = "[+]  UID: 0C CB F0 CF   ( ONUID, re-used )\n\
[+] ATQA: 00 04\n\
[+]  SAK: 08 [2]\n\
[+]    MIFARE Classic 1K\n";
        assert!(!is_banner_only(out));
    }

    #[test]
    fn card_dependent_covers_hf_and_lf_only() {
        assert!(is_card_dependent("hf mf info"));
        assert!(is_card_dependent("lf search"));
        assert!(is_card_dependent("  hf 14a reader"));
        // Device-level commands are excluded: silence is normal for them.
        assert!(!is_card_dependent("hw version"));
        assert!(!is_card_dependent("hw tune"));
        assert!(!is_card_dependent("data geto"));
    }

    /// Verbatim PM3 output for `lf t55xx set config`, which also printed the
    /// group menu and exited 0.
    #[test]
    fn flags_t55xx_group_menu() {
        let out = "-----------      ----------------------------- operations ---------------\n\
                   config           Set/Get T55XX configuration (modulation, inverted, offset, rate)\n\
                   detect           Try detecting the tag modulation\n";
        assert!(rejected_command(out).is_some());
    }

    /// A real command that found nothing must not be flagged. This is the
    /// `lf search` output for an LF card that produced no known match.
    #[test]
    fn accepts_normal_no_tag_output() {
        let out = "[=] Note: False Positives ARE possible\n\
                   [=] Checking for known tags...\n\
                   [-] No known 125/134 kHz tags found!\n\
                   [=] Searching for auth LF and special cases...\n\
                   [+] Chipset... T55xx\n\
                   [?] Hint: Try `lf t55xx` commands\n";
        assert!(rejected_command(out).is_none());
    }

    /// A successful clone must not be flagged.
    #[test]
    fn accepts_successful_read() {
        let out = "[+] Page 0\n\
                   [+]  01 | 00000000 | 00000000000000000000000000000000 | ....\n";
        assert!(rejected_command(out).is_none());
    }

    // --- device_failure(): a dropped port must not read as an empty antenna ---

    use super::device_failure;

    /// Verbatim `hf search` output from log 937, after the orphaned `lf search`
    /// child took COM24. PM3 exits 1 here. This is the text that used to be
    /// handed to the parser as a successful result, producing "No card found".
    #[test]
    fn flags_invalid_serial_port() {
        let out = "[=] Session log .../log_20260929025937.txt\n\n\
                   [+] execute command from commandline: hf search\n\n\
                   [+] Using UART port COM24\n\n\
                   [!] ERROR: invalid serial port COM24\n\n\
                   [?] Hint: Try the shell script ``./pm3 --list` to get a list of possible serial ports\n";
        assert!(device_failure(out).is_some());
    }

    #[test]
    fn flags_port_open_failures() {
        for marker in [
            "Error opening serial port COM24",
            "Failed to open the serial port",
            "Cannot open the port COM24",
        ] {
            assert!(
                device_failure(marker).is_some(),
                "should have flagged: {}",
                marker
            );
        }
    }

    /// The real `lf search` T5577 output must NOT be treated as a device
    /// failure -- this is the case `tolerate_nonzero` exists to preserve, and it
    /// still exits -10. Flagging it here would reintroduce "Scan failed".
    #[test]
    fn accepts_t55xx_search_output() {
        let out = "[=] Checking for known tags...\n\
                   [-] No known 125/134 kHz tags found!\n\
                   [=] Searching for auth LF and special cases...\n\
                   [+] Chipset... T55xx\n\
                   [?] Hint: Try `lf t55xx` commands\n";
        assert!(device_failure(out).is_none());
    }

    /// The real iCLASS `hf search` output (exit 0) must not be flagged.
    #[test]
    fn accepts_iclass_search_output() {
        let out = "[+] iCLASS / Picopass CSN: EF 82 06 03 F8 FF 12 E0 \n\n\
                   [+] Valid iCLASS tag / PicoPass tag found\n";
        assert!(device_failure(out).is_none());
    }

    /// A genuinely empty antenna must not be flagged as a device failure --
    /// that is a real "no card", not a connection problem.
    #[test]
    fn accepts_empty_antenna_output() {
        let out = "[=] Checking for known tags...\n\
                   [-] No known/supported 13.56 MHz tags found!\n";
        assert!(device_failure(out).is_none());
    }

    /// The search timeout must exceed the measured runtime of the sweeps.
    /// `lf search` measured 9-10.5s and `hf search` 10.8s on this device; the
    /// previous 8s cap killed them mid-run and orphaned the child on COM24.
    #[test]
    fn search_timeout_exceeds_measured_sweep_duration() {
        use super::{DETECT_COMMAND_TIMEOUT, SEARCH_COMMAND_TIMEOUT};
        assert!(
            SEARCH_COMMAND_TIMEOUT > std::time::Duration::from_secs(11),
            "search sweeps take ~11s; {:?} is too short",
            SEARCH_COMMAND_TIMEOUT
        );
        // The quick probe timeout is a genuinely different operation (single
        // protocol, measured 1.9-3.8s) and is allowed to stay short.
        assert!(DETECT_COMMAND_TIMEOUT < SEARCH_COMMAND_TIMEOUT);
    }

    /// `lf t55xx chk` measured 26.8s on this hardware (123-password dictionary).
    /// It ran under the 30s `PM3_COMMAND_TIMEOUT` only by a 3s margin, and the
    /// session log showed it hitting the cap: the child was killed mid-attack
    /// and the next command failed with "invalid serial port". The long-command
    /// budget must comfortably exceed the measured runtime.
    #[test]
    fn long_timeout_exceeds_measured_dictionary_attack() {
        use super::{LONG_COMMAND_TIMEOUT, PM3_COMMAND_TIMEOUT};
        assert!(
            LONG_COMMAND_TIMEOUT > std::time::Duration::from_secs(60),
            "dictionary attacks take far longer than a panel probe; {:?} is too short",
            LONG_COMMAND_TIMEOUT
        );
        // It has to be strictly longer than the default, otherwise routing the
        // command is pointless.
        assert!(LONG_COMMAND_TIMEOUT > PM3_COMMAND_TIMEOUT);
    }

    /// The dictionary attacks must be routed to the long timeout, and ordinary
    /// probes must not be. A loose `contains` match would also catch
    /// "hf mf dump", so the boundary is asserted explicitly.
    #[test]
    fn classifies_long_running_commands() {
        use super::is_long_running;
        for cmd in [
            "lf t55xx chk",
            "lf t55xx bruteforce",
            "hf 15 bruteforce",
            "hf mf bruteforce",
            "hf mfu desbrute",
            "hf mfdes chk",
            "hf mfdes bruteaid",
        ] {
            assert!(is_long_running(cmd), "{} should use the long timeout", cmd);
        }
        for cmd in [
            "lf t55xx wakeup",
            "lf t55xx read -b 0",
            "hw version",
            "hf mf dump",
            "hf search",
            // Guards the prefix-match boundary: must NOT be treated as `chk`.
            "lf t55xx chkfoo",
            "lf t55xx read",
        ] {
            assert!(
                !is_long_running(cmd),
                "{} must not use the long timeout",
                cmd
            );
        }
    }
}
